# -*- coding: utf-8 -*-
"""Intro to Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FTVtBBD2zX8JIwoI39fH8o52F44tEfwv

**Credits: All members of python community**

# Introduction

**Why learn Python?**

- Python is a general-purpose, high-level language.
- Its vast amount of libraries make it flexible to use in Data Science.

**Advantages:**
- Interpreted: Directly run the code from the source.
- Platform independent
- Open source: Free to use
- High level: No need to worry about managing memory details, etc.
- Embedded: Can be used within C/C++

# Variables reserved
"""

#Key words in Python reserved for it's built-in usage

import keyword
print("Keywords reserved in Python are:",keyword.kwlist)

"""# Namespaces - Global and Local"""

# var1 is in the global namespace
var1 = 5

def some_func():
  var2 = 6
  return var2

print(var1)
print(some_func())
#print(var2) # Can't access local space like global space

"""# Comments

**Difference Between ‘Docstrings’ and ‘Multi-line Comments?**

- Docstrings are written in the functions and classes to show how to use the program.
- Multi-line comments are used to show how a block of code works.

# Variables assignments
"""

## Variable assignment in Python

direct = 7
print(direct)

indirect = 1 if 5>3 else 0
print(indirect)

a,b,c = 5,"bag",{'key':'value'}
print(a)
print(b)
print(c)

"""# Input and Output"""

#Multiple inputs

v1,v2,v3 = [int(x) for x in input("Enter the input").split(",")]
v3

#Output format
v3=3
print('1+2={0}'.format(v3))